carsdata<-read.csv("cars.csv")
attributes(carsdata)
summary(carsdata)
str(carsdata)
names(carsdata)
carsdata$name.of.car
carsdata$speed.of.car
carsdata$distance.of.car
carsdata$name.of.car<-as.factor(carsdata$name.of.car)
names(carsdata)<-c("carname","carspeed","cardistance")
hist(carsdata$carspeed)
hist(carsdata$cardistance)
plot(carsdata$carspeed,carsdata$cardistance)
plot(carsdata$cardistance,carsdata$carspeed)
plot(carsdata$carname,carsdata$cardistance)
plot(carsdata$carname,carsdata$carspeed)
qqnorm(carsdata$carspeed)
qqnorm(carsdata$cardistance)
set.seed(42)
n<-nrow(carsdata)
cartrainsize<-round(n*0.8)
cartestsize<-(n-cartrainsize)
training_indices<-sample(1:n,size = cartrainsize)
cartrainSet<-carsdata[training_indices,]
cartestSet<-carsdata[-training_indices,]
carslinearmodel<-lm(cardistance~carspeed,cartrainSet)
summary(carslinearmodel)
carspredict<-predict(carslinearmodel,cartestSet)
carspredict