install.packages("readr")
library("readr")
IrisDataset <- read.csv(file = "iris.csv", header = TRUE, col.names = c("IrisNo","SepalLength","SepalWidth","PetalLength","PetalWidth","Species"))
attributes(IrisDataset)
summary(IrisDataset)
str(IrisDataset)
names(IrisDataset)
IrisDataset$IrisNo<-NULL
IrisDataset$Species<-as.factor(IrisDataset$Species)
summary(IrisDataset)
is.na(IrisDataset)
hist(IrisDataset$SepalLength)
hist(IrisDataset$SepalWidth)
hist(IrisDataset$PetalLength)
hist(IrisDataset$PetalWidth)
#hist(IrisDataset$Species) species not numeric
#plot(IrisDataset$Species) species not numeric
plot(IrisDataset$SepalLength)
qqnorm(IrisDataset$SepalLength)
qqnorm(IrisDataset$SepalWidth)
qqnorm(IrisDataset$PetalLength)
qqnorm(IrisDataset$PetalWidth)
#qqnorm(IrisDataset$Species) invalid 'ylim' value
n<-nrow(IrisDataset)
iristrainSize<-round(n*0.8)
iristestSize<-(n-iristrainSize)
iristrainSize
iristestSize
training_indices<-sample(1:n,size = iristrainSize)
iristrainSet<-IrisDataset[training_indices, ]
iristestSet<-IrisDataset[-training_indices, ]
set.seed(123)
LinearModel1<-lm(SepalLength~Species,iristrainSet)
set.seed(42)
LinearModel2<-lm(SepalLength~SepalWidth,iristrainSet)
set.seed(87)
LinearModel3<-lm(SepalLength~PetalLength,iristrainSet)
set.seed(101)
LinearModel4<-lm(SepalLength~PetalWidth,iristrainSet)
set.seed(214)
LinearModel5<-lm(SepalWidth~Species,iristrainSet)
set.seed(39)
LinearModel6<-lm(SepalWidth~SepalLength,iristrainSet)
set.seed(149)
LinearModel7<-lm(SepalWidth~PetalLength,iristrainSet)
set.seed(75)
LinearModel8<-lm(SepalWidth~PetalWidth,iristrainSet)
set.seed(163)
LinearModel9<-lm(PetalLength~Species,iristrainSet)
set.seed(96)
LinearModel10<-lm(PetalLength~SepalLength,iristrainSet)
set.seed(224)
LinearModel11<-lm(PetalLength~SepalWidth,iristrainSet)
set.seed(19)
LinearModel12<-lm(PetalLength~PetalWidth,iristrainSet)
set.seed(82)
LinearModel13<-lm(PetalWidth~Species,iristrainSet)
set.seed(27)
LinearModel14<-lm(PetalWidth~SepalLength,iristrainSet)
set.seed(175)
LinearModel15<-lm(PetalWidth~SepalWidth,iristrainSet)
set.seed(256)
LinearModel16<-lm(PetalWidth~PetalLength,iristrainSet)
#LinearModel17<-lm(Species~SepalLength,iristrainSet) not meaningful for factors
summary(LinearModel1)
summary(LinearModel2)
summary(LinearModel3)
summary(LinearModel4)
summary(LinearModel5)
summary(LinearModel6)
summary(LinearModel7)
summary(LinearModel8)
summary(LinearModel9)
summary(LinearModel10)
summary(LinearModel11) 
summary(LinearModel12)
summary(LinearModel13)
summary(LinearModel14)
summary(LinearModel15)
summary(LinearModel16)
prediction9<-predict(LinearModel9,iristestSet)
prediction13<-predict(LinearModel13,iristestSet)
prediction12<-predict(LinearModel12,iristestSet)
prediction16<-predict(LinearModel16,iristestSet)
prediction9
prediction13
prediction12
prediction16